# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20160904_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='dateTime',
            new_name='datetime',
        ),
    ]
