# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20160828_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
