# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.Doctor', to_field='user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.Patient', to_field='user')),
            ],
        ),
    ]
